# Generated by Django 5.2.17 on 2026-09-18 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_posts', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited posts.', null=True)),
                ('max_images_per_post', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited images.', null=True)),
                ('max_likes', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited likes.', null=True)),
                ('max_comments', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited comments.', null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscriptions', to='subscriptions.bloguser')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='BillingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('billing_date', models.DateTimeField(auto_now_add=True)),
                ('invoice_path', models.CharField(blank=True, max_length=500, null=True)),
                ('payment_status', models.CharField(default='SUCCESS', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='billing_history', to='subscriptions.bloguser')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_records', to='subscriptions.subscription')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_history', to='subscriptions.subscriptionplan')),
            ],
        ),
    ]
