"""
Django settings for django_admin project.

Generated by 'django-admin startproject' using Django 6.1.1.
"""

import os
from pathlib import Path
from dotenv import load_dotenv


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# LOAD ROOT .ENV FILE
# ============================================================
# .env is located at:
# C:\blog_management_api\.env
#
# settings.py is located at:
# C:\blog_management_api\django_admin\django_admin\settings.py

load_dotenv(BASE_DIR.parent / ".env")


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = "django-insecure-change-this-for-production"

DEBUG = True

ALLOWED_HOSTS = []


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [

    # Django built-in applications
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Our applications
    "subscriptions",
    "dashboard",

    # Django Plotly Dash
    "django_plotly_dash",
    "channels",
    "dpd_components",
    "dpd_static_support",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [

    "django.middleware.security.SecurityMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# URL CONFIGURATION
# ============================================================

ROOT_URLCONF = "django_admin.urls"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [

    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [],

        "APP_DIRS": True,

        "OPTIONS": {

            "context_processors": [

                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",

            ],
        },
    },
]


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = "django_admin.wsgi.application"


# ============================================================
# ASGI
# ============================================================

ASGI_APPLICATION = "django_admin.asgi.application"


# ============================================================
# CHANNEL LAYERS
# ============================================================

CHANNEL_LAYERS = {

    "default": {

        "BACKEND": "channels.layers.InMemoryChannelLayer"

    }

}


# ============================================================
# DJANGO PLOTLY DASH
# ============================================================

X_FRAME_OPTIONS = "SAMEORIGIN"


# ============================================================
# PLOTLY COMPONENTS
# ============================================================

PLOTLY_COMPONENTS = [

    "dpd_components",

    "dpd_static_support",

]


# ============================================================
# STATIC FILE FINDERS
# ============================================================

STATICFILES_FINDERS = [

    "django.contrib.staticfiles.finders.FileSystemFinder",

    "django.contrib.staticfiles.finders.AppDirectoriesFinder",

    "django_plotly_dash.finders.DashAssetFinder",

    "django_plotly_dash.finders.DashComponentFinder",

    "django_plotly_dash.finders.DashAppDirectoryFinder",

]


# ============================================================
# DATABASE
# ============================================================
# Existing MySQL database used by FastAPI.
#
# Database:
# blog_management_api
#
# MySQL:
# 127.0.0.1:3306

DATABASES = {

    "default": {

        "ENGINE": "django.db.backends.mysql",

        "NAME": os.getenv(
            "MYSQL_DATABASE",
            "blog_management_api"
        ),

        "USER": os.getenv(
            "MYSQL_USER",
            "root"
        ),

        "PASSWORD": os.getenv(
            "MYSQL_PASSWORD",
            ""
        ),

        "HOST": os.getenv(
            "MYSQL_HOST",
            "127.0.0.1"
        ),

        "PORT": os.getenv(
            "MYSQL_PORT",
            "3306"
        ),

    }

}


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        "NAME":
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator",
    },

]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = "static/"


# ============================================================
# MEDIA FILES
# ============================================================

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR.parent / "media"


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ============================================================
# EMAIL CONFIGURATION
# ============================================================

EMAIL_BACKEND = (
    "django.core.mail.backends.console.EmailBackend"
)


EMAIL_HOST = os.getenv(
    "SMTP_HOST",
    "smtp.gmail.com"
)


EMAIL_PORT = int(
    os.getenv(
        "SMTP_PORT",
        "587"
    )
)


EMAIL_USE_TLS = True


EMAIL_HOST_USER = os.getenv(
    "SMTP_USERNAME",
    ""
)


EMAIL_HOST_PASSWORD = os.getenv(
    "SMTP_PASSWORD",
    ""
)


DEFAULT_FROM_EMAIL = os.getenv(
    "SMTP_FROM_EMAIL",
    "noreply@example.com"
)